max-amount: 64

# Whether to drop items to the ground if the target inventory is full
drop-overflow: false

# When dropping overflow, whether to drop items naturally (with a random velocity) or not
drop-naturally: false

# Can be a number, or "stack" to use the item's max stack size
default-amount: stack